version: "3.1"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password  
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    links:
      - backend
  backend:
    image: employee/backend
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=chef
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"     