version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password 
    ports:
      - "27017:27017" 
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archieve:/Database/dev.archieve
      - ./database/production:/Database/production
    links:
      - backend
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=chef
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
    ports:
      - "8081:8081" 
    links:
      - mongo
    restart: unless-stopped
  
  backend:
    image: employee/backend
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"        